### ISSUE TITLE
No module named 'evalidate'

### ISSUE THREAD

**Issue by tuoluogongfang** [alt-key-project/comfyui-dream-project#3]
File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-dream-project-master\__init__.py", line 16, in <module>
    from .calculate import *
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-dream-project-master\calculate.py", line 4, in <module>
    from evalidate import Expr, EvalException, base_eval_model
ModuleNotFoundError: No module named 'evalidate'

Cannot import D:\Blender_ComfyUI\ComfyUI\custom_nodes\comfyui-dream-project-master module for custom nodes: No module named 'evalidate'

Where can I find the model mentioned in this question please, thanks!

**Comment by alt-key-project** [comment]
One of the current problems with comfyui is that there is no good way to pull additional dependencies after first installation of a custom node pack. The dependency is installed automatically by the manager so if you uninstall and install the dream project nodes it should be added for you. Otherwise you may manually run a "python.exe -s -m pip install -r requirements.txt" using the right python executable for your comfyui installation.
